name: CI - Build & Test (frontend + backend)

on:
  push:
    branches: [development, main]
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
      - "backend/**"

permissions:
  contents: read
  id-token: write

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }} # e.g., week08container.azurecr.io
  IMAGE_TAG: ${{ github.sha }}

jobs:
  # ---- Backend (product + order) test/build/push in one job with a matrix
  backend:
    name: Backend CI (product & order)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [product, order]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        run: |
          az acr login --name "$ACR_NAME"

      # (Optional) quick health/test step – leave simple as student but still shows testing
      - name: Run basic tests
        working-directory: backend/${{ matrix.service }}
        run: |
          echo "Running tests for ${{ matrix.service }} (placeholder)"
          # e.g., pytest -q || exit 1

      - name: Build image
        working-directory: backend/${{ matrix.service }}
        run: |
          docker build -t $ACR_LOGIN_SERVER/${{ matrix.service }}:${IMAGE_TAG} .
          # also tag by branch for convenience
          if [ "${{ github.ref_name }}" = "main" ]; then
            docker tag $ACR_LOGIN_SERVER/${{ matrix.service }}:${IMAGE_TAG} $ACR_LOGIN_SERVER/${{ matrix.service }}:prod
          else
            docker tag $ACR_LOGIN_SERVER/${{ matrix.service }}:${IMAGE_TAG} $ACR_LOGIN_SERVER/${{ matrix.service }}:dev
          fi

      - name: Push image
        run: |
          docker push $ACR_LOGIN_SERVER/${{ matrix.service }}:${IMAGE_TAG}
          if [ "${{ github.ref_name }}" = "main" ]; then
            docker push $ACR_LOGIN_SERVER/${{ matrix.service }}:prod
          else
            docker push $ACR_LOGIN_SERVER/${{ matrix.service }}:dev
          fi

  # ---- Frontend build/push
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        run: |
          az acr login --name "$ACR_NAME"

      - name: Build image
        working-directory: frontend
        run: |
          docker build -t $ACR_LOGIN_SERVER/frontend:${IMAGE_TAG} .
          if [ "${{ github.ref_name }}" = "main" ]; then
            docker tag $ACR_LOGIN_SERVER/frontend:${IMAGE_TAG} $ACR_LOGIN_SERVER/frontend:prod
          else
            docker tag $ACR_LOGIN_SERVER/frontend:${IMAGE_TAG} $ACR_LOGIN_SERVER/frontend:dev
          fi

      - name: Push image
        run: |
          docker push $ACR_LOGIN_SERVER/frontend:${IMAGE_TAG}
          if [ "${{ github.ref_name }}" = "main" ]; then
            docker push $ACR_LOGIN_SERVER/frontend:prod
          else
            docker push $ACR_LOGIN_SERVER/frontend:dev
          fi
