# .github/workflows/frontend-cd.ymls
name: CD — Deploy Frontend (AKS, no IP injection)

on:
  push:
    branches: ["main"]
    paths:
      - "k8s/**"
      - ".github/workflows/frontend-cd.yml"
  workflow_dispatch:
    inputs:
      aks_cluster_name:
        description: "AKS cluster name"
        required: true
        default: "clusterweek08"
      aks_resource_group:
        description: "AKS resource group"
        required: true
        default: "week08-resource-group"

permissions:
  id-token: write
  contents: read

env:
  NAMESPACE: week08
  PRODUCT_API_URL: http://product-service:8000
  ORDER_API_URL: http://order-service:8000

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group "${{ github.event.inputs.aks_resource_group || 'week08-resource-group' }}" \
            --name "${{ github.event.inputs.aks_cluster_name || 'clusterweek08' }}" \
            --overwrite-existing

      - name: Create namespace (idempotent)
        run: kubectl get ns $NAMESPACE || kubectl create ns $NAMESPACE

      - name: Apply frontend manifests
        run: |
          # If your Deployment reads env from ConfigMap/Secret, apply those first.
          # kubectl apply -f k8s/config/
          kubectl apply -f k8s/frontend/

      # Temporary helper: patch env on the Deployment if you aren't using a ConfigMap yet
      - name: Patch env for API URLs
        run: |
          kubectl set env deploy/frontend \
            \
            PRODUCT_API_URL=${{ env.PRODUCT_API_URL }} \
            ORDER_API_URL=${{ env.ORDER_API_URL }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deploy/frontend --timeout=120s
