# .github/workflows/frontend_ci.yml
name: Frontend CI — Build & Push (SHA tags)

on:
  push:
    branches: ["**"]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_ci.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }} # e.g. myregistry.azurecr.io
  ACR_NAME: ${{ secrets.ACR_NAME }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ACR login via az
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Cache npm (frontend)
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: npm-

      - name: Build & push Frontend image (SHA tag)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Logout from Azure
        if: always()
        run: az logout
